// This file was generated by UCC. Manual changes are discouraged as they may be overwritten in future generations.
// See https://github.com/ClaudioMota/UCC for more in information.

#ifndef ucc_LEXER_FUNCTIONS_HEADER
#define ucc_LEXER_FUNCTIONS_HEADER 1
#ifdef __cplusplus
extern "C" {
#endif

extern int (**ucc_lexerFunctions)(int* state, int input);
extern int ucc_lexerFunctionCount;

bool ucc_shouldIgnoreToken(Token* token);

#ifdef __cplusplus
}
#endif
#endif
