// This file was generated by UCC. Manual changes are discouraged as they may be overwritten in future generations.
// See https://github.com/ClaudioMota/UCC for more in information.

#ifndef ucc_PARSER_HEADER
#define ucc_PARSER_HEADER 1
#ifdef __cplusplus
extern "C" {
#endif

enum ucc_Tokens
{
  ucc_T_UNKNOWN = -2,
  ucc_T_END_OF_INPUT = -1,
  ucc_T_identifier,
  ucc_T_semicolon,
  ucc_T_to,
  ucc_T_comma,
  ucc_T_blank,
  ucc_T_breakLine,
  ucc_T_comment,
  ucc_T_helpers,
  ucc_T_tokens,
  ucc_T_productions,
  ucc_T_reducer,
  ucc_T_attrib,
  ucc_T_sum,
  ucc_T_sub,
  ucc_T_mult,
  ucc_T_or,
  ucc_T_reduce,
  ucc_T_question,
  ucc_T_o_parentheses,
  ucc_T_c_parentheses,
  ucc_T_o_brackets,
  ucc_T_c_brackets,
  ucc_T_charLiteral,
  ucc_T_decimal
};

extern int (**ucc_lexerFunctions)(int* state, int input);
extern int ucc_lexerFunctionCount;

bool ucc_shouldIgnoreToken(Token* token);
bool ucc_visit(Production* production, VisitData* visitData);
bool ucc_visitNodes(Production* production, VisitData* visitData);
extern bool ucc_nodeRedundancyTable[];

Parser ucc_parse(ProductionContainer* allProductions, Token* tokens);

#ifdef __cplusplus
}
#endif
#endif
